export {Landing} from "./Landing/Landing"
export {Feeds} from "./feeds/Feeds"
export {Login} from "./Authpages/Login"
export {SignUp} from "./Authpages/SignUp"
export {Profile} from "./Profile/Profile"
export {Setting} from "./Setting/Setting"